import Head from 'next/head';
import Image from 'next/image';

const Home = () => {
	return (
		<div className='flex items-center justify-center w-screen h-screen bg-gray-900 text-white'>
			<Head>
				<title>SL Groups</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div>Home</div>
		</div>
	);
};

export default Home;

